#### 导入库

In [175]:
import pandas as pd
import numpy as np
import tushare as ts
from pandas.core.frame import DataFrame
from pandas import Series
pd.set_option('expand_frame_repr',False)
import time
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

#### 连接数据库

In [170]:
# 连接数据库
engine = create_engine('mysql://root:K@ppy213@localhost/sjfx?charset=utf8')

#### 定义常量

In [171]:
path='D:/TuShare/20190820_600570.xlsx'
df=pd.read_excel(path)

In [182]:
df.head(10)

         date   open   high  close    low     volume  price_change  p_change     ma5    ma10    ma20      v_ma5     v_ma10     v_ma20
0  2019-08-20  71.90  72.60  70.86  70.68  210256.44         -1.09     -1.51  68.316  66.990  68.287  191538.89  158284.03  173181.20
1  2019-08-19  68.03  71.98  71.95  68.03  337893.59          5.08      7.60  67.262  66.410  68.252  169273.97  162381.25  175230.77
2  2019-08-16  66.00  67.98  66.87  65.81  170518.73          0.78      1.18  66.292  65.907  68.018  127189.41  149212.74  164774.51
3  2019-08-15  64.00  66.20  66.09  63.68  120435.88          0.28      0.42  65.968  66.116  68.050  120584.07  154751.22  162081.37
4  2019-08-14  67.30  67.39  65.81  65.57  118589.80          0.22      0.34  65.950  66.644  68.080  125070.74  156855.33  161208.13
5  2019-08-13  66.50  66.66  65.59  65.38   98931.83         -1.51     -2.25  65.664  67.172  68.195  125029.17  159462.98  161048.06
6  2019-08-12  65.30  67.10  67.10  65.25  127470.80          1.85      2.83  65.558  67.685  68.338  155488.54  167452.88  161924.61
7  2019-08-09  66.20  67.15  65.25  64.60  137492.06         -0.75     -1.14  65.522  68.010  68.403  171236.06  165999.26  167593.47
8  2019-08-08  65.33  66.26  66.00  65.33  142869.20          1.62      2.52  66.264  68.512  68.399  188918.36  172660.89  165218.72
9  2019-08-07  65.49  65.56  64.38  64.38  118381.96         -0.68     -1.04  67.338  69.021  68.360  188639.91  176995.62  164018.31

In [181]:
# df.head(10)
# df.dtypes
# # 随机抽取10行
# df.sample(n=10)
# # 随机抽取60%的行
# df.sample(frac=0.6)
# 只看固定某一列的数据
# df['close']
df.loc[]

KeyError: '510'

### 字典和列的使用

In [27]:
# 股票持仓
position_dict = {'600570.SH':500,'000256.SZ':1000,'300001.SZ':5000}
position_dict

{'600570.SH': 500, '000256.SZ': 1000, '300001.SZ': 5000}

In [31]:
# 修改position_dict数据
position_dict['600570.SH']=10000
position_dict

{'600570.SH': 10000, '000256.SZ': 1000, '300001.SZ': 5000}

In [32]:
# 新开仓股票，新增数据
position_dict['000001.SH']=2500
position_dict

{'600570.SH': 10000, '000256.SZ': 1000, '300001.SZ': 5000, '000001.SH': 2500}

In [33]:
# 删除部分数据
del position_dict['600570.SH']
position_dict

{'000256.SZ': 1000, '300001.SZ': 5000, '000001.SH': 2500}

In [29]:
# 股票去重
position=['000001.SZ','000002.SZ','000003.SZ','000004.SZ','000005.SZ']
to_buy=['000004.SZ','000002.SH','000003.SZ','000010.SH']
will_being=position+to_buy
will_being

['000001.SZ',
 '000002.SZ',
 '000003.SZ',
 '000004.SZ',
 '000005.SZ',
 '000004.SZ',
 '000002.SH',
 '000003.SZ',
 '000010.SH']

In [30]:
will_being=set(will_being)
will_being

{'000001.SZ',
 '000002.SH',
 '000002.SZ',
 '000003.SZ',
 '000004.SZ',
 '000005.SZ',
 '000010.SH'}

### DataFrame使用

In [15]:
data={'age':[13,18,10,20,31],
      'height':[178,198,201,167,158]}
data

{'age': [13, 18, 10, 20, 31], 'height': [178, 198, 201, 167, 158]}

In [16]:
df_data=pd.DataFrame(data)
df_data

   age  height
0   13     178
1   18     198
2   10     201
3   20     167
4   31     158

### 二级索引

In [26]:
s = DataFrame(np.random.randint(0,150,size=(6,3)),
             columns=['语文','数学','Python'],
             index=[['Michale','Michale','Lisa','Lisa','PO','PO'],['Mid','End','Mid','End','Mid','End']])
s

             语文  数学  Python
Michale Mid  37  46     116
        End  68   5      34
Lisa    Mid  87  77      46
        End  28  62     136
PO      Mid  65  70      16
        End  54  78       2

In [33]:
s2 = DataFrame(np.random.randint(0,150,size=(6,3)),
             columns=['语文','数学','Python'],
             index=pd.MultiIndex.from_arrays([['张三','张三','李四','李四','王二麻子','王二麻子'],['Mid','End','Mid','End','Mid','End']]))
s2

           语文   数学  Python
张三   Mid  100   83      68
     End   84  124      72
李四   Mid   24  137      14
     End   84  134      47
王二麻子 Mid   93   49     116
     End   11   67      10

### concat&merge级联

In [35]:
num=np.random.randint(0,100,size=(3,3))
num

array([[81, 20, 86],
       [64,  8,  6],
       [ 3, 10, 48]])

In [37]:
np.concatenate((num,num),axis=0)

array([[81, 20, 86],
       [64,  8,  6],
       [ 3, 10, 48],
       [81, 20, 86],
       [64,  8,  6],
       [ 3, 10, 48]])

In [38]:
np.concatenate((num,num),axis=1)

array([[81, 20, 86, 81, 20, 86],
       [64,  8,  6, 64,  8,  6],
       [ 3, 10, 48,  3, 10, 48]])

In [39]:
list1=[1,2,3,4]
list1

[1, 2, 3, 4]

### 处理账单myMoney.xls

In [4]:
myMoney_file='D:/TuShare/myMoney.xls'

In [8]:
df_money=pd.read_excel(myMoney_file)
df_money

,交易种类,类别,子类,账户1,账户2,花费,人员,商家,事件,日期,详细
0,支出,饮食,三餐,现金,NaN,2.0,老婆,NaN,NaN,2019-09-04 10:03:22,NaN
1,支出,饮食,超市,现金,NaN,40.0,老公,NaN,NaN,2019-09-03 20:03:59,NaN
2,支出,饮食,超市,现金,NaN,11.0,老婆,NaN,NaN,2019-09-03 18:34:25,口香糖
3,支出,娱乐,健身,现金,NaN,81.0,老公,NaN,NaN,2019-09-02 21:17:58,趣跑吧
4,支出,衣物,衣裤袜,现金,NaN,141.0,老婆,NaN,NaN,2019-09-01 23:43:04,买衣服裤子
5,支出,饮食,超市,现金,NaN,38.0,老公,NaN,NaN,2019-09-01 21:42:38,NaN
6,支出,饮食,三餐,现金,NaN,26.0,老公,NaN,NaN,2019-09-01 18:12:11,NaN
7,支出,通讯,移动,现金,NaN,148.0,老公,NaN,NaN,2019-09-01 10:38:17,NaN
8,支出,轿车,停车,现金,NaN,280.0,老公,NaN,NaN,2019-09-01 10:01:55,车位管理费，4个月
9,支出,轿车,维修,现金,NaN,165.0,老公,NaN,NaN,2019-09-01 09:50:57,大众93MZ9，38250KM
10,支出,饮食,三餐,现金,NaN,9.0,老婆,NaN,NaN,2019-09-01 09:41:51,NaN
11,支出,轿车,停车,现金,NaN,1800.0,老公,NaN,NaN,2019-08-31 23:17:47,车位费
12,支出,饮食,三餐,现金,NaN,90.0,老婆,NaN,NaN,2019-08-31 19:56:33,NaN
13,支出,交通,公交,现金,NaN,8.0,老公,NaN,NaN,2019-08-31 16:15:03,美团单车月卡
14,支出,居家,日常用品,现金,NaN,12.0,老公,NaN,NaN,2019-08-31 00:04:25,支付宝全球骑士卡
15,支出,饮食,三餐,现金,NaN,27.0,老婆,NaN,NaN,2019-08-30 22:25:48,NaN
16,支出,轿车,油费,现金,NaN,100.0,老公,NaN,NaN,2019-08-30 19:03:39,NaN
17,支出,医美,美容费,现金,NaN,30.0,老公,NaN,NaN,2019-08-29 22:35:26,理发
18,支出,人情,送礼请客,现金,NaN,184.0,老公,NaN,NaN,2019-08-29 21:26:13,请欢欢一家人吃饭
19,支出,饮食,三餐,现金,NaN,6.0,老公,NaN,NaN,2019-08-29 18:05:11,NaN
20,支出,交通,公交,现金,NaN,20.0,老公,NaN,NaN,2019-08-29 17:36:12,NaN
21,支出,衣物,鞋帽包,现金,NaN,69.0,老公,NaN,NaN,2019-08-29 11:43:31,小米胸包
22,支出,饮食,三餐,现金,NaN,45.0,老公,NaN,NaN,2019-08-28 15:20:06,聚餐，同事离职，散伙饭
23,支出,饮食,三餐,现金,NaN,24.0,老婆,NaN,NaN,2019-08-28 11:34:36,NaN
24,支出,饮食,超市,现金,NaN,16.0,老公,NaN,NaN,2019-08-27 21:29:52,NaN
25,支出,居家,电子设备,现金,NaN,100.0,老公,NaN,NaN,2019-08-27 21:27:22,送小宋耳机
26,支出,饮食,三餐,现金,NaN,16.0,老公,NaN,NaN,2019-08-27 13:29:54,NaN
27,支出,饮食,三餐,现金,NaN,8.0,老婆,NaN,NaN,2019-08-26 17:38:44,NaN
28,支出,饮食,超市,现金,NaN,5.0,老公,NaN,NaN,2019-08-26 16:37:33,NaN
29,支出,饮食,超市,现金,NaN,17.0,老婆,NaN,NaN,2019-08-26 12:54:38,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4857,支出,杂项,其他支出,现金,NaN,135.9,老公,NaN,NaN,2014-01-28 19:38:47,年货，牛肉干
4858,支出,饮食,三餐,现金,NaN,3.0,老公,NaN,NaN,2014-01-28 09:20:17,NaN
4859,支出,饮食,三餐,现金,NaN,12.0,老公,NaN,NaN,2014-01-27 19:11:43,午饭
4860,支出,饮食,三餐,现金,NaN,3.0,老公,NaN,NaN,2014-01-27 09:19:57,食堂包子
4861,支出,饮食,三餐,现金,NaN,6.7,老公,NaN,NaN,2014-01-26 19:37:10,菜市场买青菜
4862,支出,饮食,三餐,现金,NaN,10.0,老公,NaN,NaN,2014-01-26 11:30:49,宜宾燃面
4863,支出,杂项,其他支出,现金,NaN,299.0,老公,NaN,NaN,2014-01-25 20:08:37,给爸买的年货，松下剃须刀
4864,支出,杂项,其他支出,现金,NaN,30.0,老公,NaN,NaN,2014-01-25 17:46:50,赛格广场维修手机，换充电接口
4865,支出,饮食,超市,现金,NaN,9.7,老公,NaN,NaN,2014-01-25 15:21:48,NaN
4866,支出,交通,公交,现金,NaN,4.0,老公,NaN,NaN,2014-01-25 13:39:48,公交卡次卡充值
4867,支出,交通,公交,现金,NaN,50.0,老公,NaN,NaN,2014-01-25 11:12:01,地铁卡充值
4868,支出,饮食,三餐,现金,NaN,3.0,老公,NaN,NaN,2014-01-25 11:07:21,NaN
4869,支出,杂项,其他支出,现金,NaN,20.0,老公,NaN,NaN,2014-01-25 10:34:37,三星手机电池座充
4870,支出,饮食,三餐,现金,NaN,2.5,老公,NaN,NaN,2014-01-24 09:00:15,NaN
4871,支出,进修,培训,现金,NaN,260.0,老公,NaN,NaN,2014-01-22 13:35:50,驾校科目二补考费用
4872,支出,交通,公交,现金,NaN,5.0,老公,NaN,NaN,2014-01-22 07:54:46,驾考科目二交通费
4873,支出,医美,药品费,现金,NaN,5.0,老公,NaN,NaN,2014-01-21 19:47:30,单位需要的2天病假医疗证明
4874,支出,杂项,其他支出,现金,NaN,10.0,老公,NaN,NaN,2014-01-21 18:46:27,驾校场地学车
4875,支出,饮食,三餐,现金,NaN,3.8,老公,NaN,NaN,2014-01-21 13:31:20,NaN
4876,支出,娱乐,聚会,现金,NaN,34.0,老公,NaN,NaN,2014-01-20 18:50:07,环球中心晚餐+饮料
4877,支出,饮食,超市,现金,NaN,45.0,老公,NaN,NaN,2014-01-19 20:08:14,欧尚面包及早餐奶粉
4878,支出,交通,公交,现金,NaN,7.0,老公,NaN,NaN,2014-01-19 14:00:42,公交卡次卡充值
4879,支出,饮食,超市,现金,NaN,3.5,老公,NaN,NaN,2014-01-19 14:00:07,格瓦拉饮料
4880,支出,交通,公交,现金,NaN,50.0,老公,NaN,NaN,2014-01-15 20:07:23,地铁电子钱包充值
4881,支出,饮食,超市,现金,NaN,10.0,老公,NaN,NaN,2014-01-12 21:50:12,橘子
4882,支出,杂项,其他支出,现金,NaN,59.0,老公,NaN,NaN,2014-01-12 10:00:47,购买手机电池-品胜品牌
4883,支出,娱乐,电影,现金,NaN,19.0,老公,NaN,NaN,2014-01-05 21:52:45,峨影1958电影院看电影
4884,支出,居家,电费,现金,NaN,30.0,老公,NaN,NaN,2014-01-05 20:00:47,电费
4885,支出,通讯,移动,现金,NaN,20.0,老公,NaN,NaN,2014-01-03 21:47:20,宽带费用
4886,支出,饮食,三餐,现金,NaN,100.0,老公,NaN,NaN,2014-01-01 14:48:59,公司食堂饭卡充值

In [11]:
df_money.to_sql('mymoney',engine,if_exists='append')

### Series基础

In [37]:
trade_volume=[1100,1400,1800,700]
stock=['平安银行','恒生电子','赢时胜','长亮科技']
stock

['平安银行', '恒生电子', '赢时胜', '长亮科技']

In [38]:
trade_volume_series=pd.Series(trade_volume,index=stock)
trade_volume_series

平安银行    1100
恒生电子    1400
赢时胜     1800
长亮科技     700
dtype: int64

In [40]:
# Series = list + dict
holding_position={'平安银行':1000, '恒生电子':800, '赢时胜':1800, '长亮科技':9000}
holding_position_series=pd.Series(holding_position)
holding_position_series

平安银行    1000
恒生电子     800
赢时胜     1800
长亮科技    9000
dtype: int64

In [41]:
# 常数构建series
buy_holding_position=pd.Series(1000,index=stock)
buy_holding_position

平安银行    1000
恒生电子    1000
赢时胜     1000
长亮科技    1000
dtype: int64

In [46]:
buy_holding_position['恒生电子']

1000

In [47]:
list_a=['恒生电子','赢时胜']
buy_holding_position[list_a]

恒生电子    1000
赢时胜     1000
dtype: int64

In [48]:
buy_holding_position[:2]

平安银行    1000
恒生电子    1000
dtype: int64

In [49]:
buy_holding_position[3:]

长亮科技    1000
dtype: int64

In [50]:
buy_holding_position[3:10]

长亮科技    1000
dtype: int64

In [59]:
buy_holding_position[-2:]

赢时胜     1000
长亮科技    1000
dtype: int64

In [51]:
buy_holding_position.abs

<bound method NDFrame.abs of 平安银行    1000
恒生电子    1000
赢时胜     1000
长亮科技    1000
dtype: int64>

In [58]:
buy_holding_position[buy_holding_position>100]

平安银行    1000
恒生电子    1000
赢时胜     1000
长亮科技    1000
dtype: int64

In [60]:
buy_holding_position.drop('长亮科技')

平安银行    1000
恒生电子    1000
赢时胜     1000
dtype: int64

In [61]:
df=pd.DataFrame(buy_holding_position)
df

         0
平安银行  1000
恒生电子  1000
赢时胜   1000
长亮科技  1000

In [62]:
df1=df.T
df1

   平安银行  恒生电子   赢时胜  长亮科技
0  1000  1000  1000  1000

In [63]:
df1.loc[:,'市北高新']=[500]
df1

   平安银行  恒生电子   赢时胜  长亮科技  市北高新
0  1000  1000  1000  1000   500

In [64]:
df1.iloc[0,0]=2000
df1

   平安银行  恒生电子   赢时胜  长亮科技  市北高新
0  2000  1000  1000  1000   500

In [68]:
df1.drop(columns=['平安银行'])

   恒生电子   赢时胜  长亮科技  市北高新
0  1000  1000  1000   500

In [72]:
df1.sort_values(by='赢时胜',ascending=True)

   平安银行  恒生电子   赢时胜  长亮科技  市北高新
0  2000  1000  1000  1000   500

In [82]:
position1={'平安银行':1000, '恒生电子':800, '赢时胜':200}
position2={'成都银行':2000, '金证股份':600, '新钢股份':600}
position3={'中信银行':3000, '银之杰':900, '用友网络':300}
p1=pd.Series(position1)
p2=pd.Series(position2)
p3=pd.Series(position3)
p1
p2
p3

中信银行    3000
银之杰      900
用友网络     300
dtype: int64

In [85]:
p=pd.DataFrame(p1)
pm=p.T
pm

   平安银行  恒生电子  赢时胜
0  1000   800  200

In [ ]:
# 取出数据
# 上证 & 深证 涨跌百分比
sh_pct=
sz_pct=

### 数据透视表

In [97]:
# 读取本地表格数据
data=pd.read_excel(path)
data.head(5)

,date,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20
0,2019-08-20,71.90,72.60,70.86,70.68,210256.44,-1.09,-1.51,68.316,66.990,68.287,191538.89,158284.03,173181.20
1,2019-08-19,68.03,71.98,71.95,68.03,337893.59,5.08,7.60,67.262,66.410,68.252,169273.97,162381.25,175230.77
2,2019-08-16,66.00,67.98,66.87,65.81,170518.73,0.78,1.18,66.292,65.907,68.018,127189.41,149212.74,164774.51
3,2019-08-15,64.00,66.20,66.09,63.68,120435.88,0.28,0.42,65.968,66.116,68.050,120584.07,154751.22,162081.37
4,2019-08-14,67.30,67.39,65.81,65.57,118589.80,0.22,0.34,65.950,66.644,68.080,125070.74,156855.33,161208.13

In [95]:
# pivot_table
# 运算今天的所有数据
data.pivot_table('open',index='date',columns='close',aggfunc='mean').fillna(0)

close,36.06,36.16,36.6,36.61,36.71,36.82,36.97,37.38,37.44,37.49,...,91.9,91.92,92.0,94.63,95.29,96.3,97.33,97.39,99.0,100.08
date,,,,,,,,,,,,,,,,,,,,,
2017-02-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-02-21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-02-22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-02-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-02-24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-02-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-02-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-07-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# 分类求和
data.pivot_table('','')

In [99]:
# 分类计算，最大值/最小值
def rateFunc(group):
    return group.max()/group.min()

data.pivot_table('open',index='date',columns='close',aggfunc=rateFunc).fillna(0)

close,36.06,36.16,36.6,36.61,36.71,36.82,36.97,37.38,37.44,37.49,...,91.9,91.92,92.0,94.63,95.29,96.3,97.33,97.39,99.0,100.08
date,,,,,,,,,,,,,,,,,,,,,
2017-02-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-02-21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-02-22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-02-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-02-24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-02-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-02-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-03-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-07-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-07-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-08-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [108]:
np.arange(100,200,5)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [111]:
np.random.randint(10,15)

12

In [116]:
"%.2f"%np.random.random()

'0.93'

### 抠图教程

In [127]:
from removebg import RemoveBg
import os

In [134]:
rmbg=RemoveBg("WPZ2Q4fraseKfAN9PPxxxxxx","error.log")
# path="D:\\TuShare\\picture"
path='%s/picture'%os.getcwd()
path

'C:\\Users\\qiao.gu/picture'

In [135]:
os.listdir(path)
for pic in os.listdir(path):
    print(pic)

test01.jpg
test02.jpg
test03.jpg
test04.jpg

In [136]:
for pic in os.listdir(path):
    rmbg.remove_background_from_img_file("%s\%s"%(path,pic))

In [157]:
symbol1='bctusd'
symbol2='ethusd'
symbol='btcusd,ethusd,xrpusd'
print(symbol1+','+symbol2)
print(symbol1*3)
print('*'*3)

bctusd,ethusd
bctusdbctusdbctusd
***

In [148]:
symbol1.startswith('bct')

True

In [150]:
print('btc' in symbol1)

False

In [151]:
symbol1.replace('bct','aaaaabbbbb')

'aaaaabbbbbusd'

In [155]:
print('abcdfd,efdcdfd'.replace('dfd','bbbbbb'))

abcbbbbbb,efdcbbbbbb

In [158]:
print(symbol.split(','))

['btcusd', 'ethusd', 'xrpusd']

In [159]:
print(symbol.split(',')[0])

btcusd

In [160]:
print(symbol.split('usd'))

['btc', ',eth', ',xrp', '']

In [161]:
symbol_list=['btcusd', 'ethusd', 'xrpusd']
symbol_list

['btcusd', 'ethusd', 'xrpusd']

In [164]:
print('-'.join(symbol_list))

btcusd-ethusd-xrpusd

In [165]:
symbol3='        bctusd'
symbol3

'        bctusd'

In [168]:
symbol3.strip()

'bctusd'